language: r
sudo: false
cache: packages

repos:
  CRAN: https://cloud.r-project.org

env: NOT_CRAN="true"

matrix:
  include:

  - os: linux
    dist: trusty
    r: oldrel

  - os: linux
    dist: trusty
    r: release

  - os: linux
    dist: trusty
    r: devel

  - os: osx
    osx_image: xcode9
    latex: false

r_build_args: '--no-build-vignettes'
r_check_args: '--as-cran --ignore-vignettes --no-examples'

branches:
  only:
    - master
    - release
    - dev

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'withr::with_envvar(c(NOT_CRAN="true"), {covr::codecov()})'

